baseURL = 'https://tealab.example.org/'
languageCode = 'en'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
title = 'Tea Lab'
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

[pagination]
  pagerSize = 5

# Theme
# theme = "paper"

# Menu
[menu]
  [[menu.main]]
    identifier = "artisan-studio"
    name = "The Artisanâ€™s Studio"
    url = "/artisan-studio/"
    weight = 10
  [[menu.main]]
    identifier = "tasting-room"
    name = "The Tasting Room"
    url = "/tasting-room/"
    weight = 20

[params]
  color = 'linen'
  avatar = ''
  name = 'Latest Articles'
  bio = 'Explore the world of tea'
  mainSections = ['blogs']

# Needed to render raw HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"