baseURL = 'https://tealab.example.org/'
languageCode = 'zh'
defaultContentLanguage = 'zh'
defaultContentLanguageInSubdir = false
title = '小茶坊'
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

[pagination]
  pagerSize = 3

# Theme
theme = "paper"

# Menu
[menu]
  [[menu.main]]
    identifier = "blogs"
    name = "博客"
    url = "/blogs/"
    weight = 10
  [[menu.main]]
    identifier = "tea-families"
    name = "茶类"
    url = "/tea-families/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 30

[params]
  color = 'linen'
  avatar = ''
  name = '小茶坊'
  bio = '探索茶的世界'
  mainSections = ['blogs']

# Needed to render raw HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
