baseURL = 'https://tealab.example.org/'
languageCode = 'en'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
title = 'Tea Lab'
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

[pagination]
  pagerSize = 5

# Theme
# theme = "paper"

# Menu
[menu]
  [[menu.main]]
    identifier = "tea-heritage"
    name = "Tea Heritage"
    url = "/tea-heritage/"
    weight = 10
  [[menu.main]]
    identifier = "artisan-guide"
    name = "The Artisanâ€™s Guide"
    url = "/artisan-guide/"
    weight = 20
  [[menu.main]]
    identifier = "tasting-room"
    name = "The Tasting Room"
    url = "/tasting-room/"
    weight = 30

[params]
  color = 'linen'
  avatar = ''
  name = 'Latest Articles'
  bio = 'Explore the world of tea'
  mainSections = ['blogs']

# Needed to render raw HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"